ClassicalTrainingArguments:
  num_train_epochs: 1
  train_batch_size: 32
  optimizer: adam
  metrics: accuracy
  loss: categorical_crossentropy

QuantumTrainingArguments:
  num_train_epochs: 1
  train_batch_size: 32
