data_ingetion:
  root_dir: dataset/data_ingestion
  local_data_file: dataset/data_ingestion/archive.zip
  unzip_dir: dataset/data_ingestion

classical_model_config:
  root_dir: model/
  data_path: dataset/data_ingestion
  model_ckpt: model/classical/
  model_name: ResNet50
  num_classes: 23
  img_size: [256, 256]

quantum_model_config:
  root_dir: model/
  data_path: dataset/data_ingestion
  model_ckpt: model/quantum/
  model_name: ResNet50
  num_classes: 23
  img_size: [256, 256]
